### ISSUE TITLE
Navigating off of the https://nuxtjs.org/v3/ errors with certain nav options

### ISSUE THREAD

**Issue by CodyBontecou** [nuxt/website-v2#1705]
Learn → Docs or Examples errors out with the following error:

`404 (/_nuxt/_docus/5b8349c3/data:docus:navigation.json)`

**Comment by CodyBontecou** [comment]
This happens when clicking on the nav link (and not going to a new tab)

**Comment by ctwhome** [comment]
also pages like this https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-build/
